In [31]:
import pandas as pd
import numpy as np

In [32]:
PATH=r"C:\Users\LENOVO\Desktop\Shopping\AI_Shopping_Intelligence\data\Main_review.csv"

In [33]:
df=pd.read_csv(PATH)
df.head()

,category,rating,label,text_
0,Home_and_Kitchen_5,5.0,CG,"Love this! Well made, sturdy, and very comfor..."
1,Home_and_Kitchen_5,5.0,CG,"love it, a great upgrade from the original. I..."
2,Home_and_Kitchen_5,5.0,CG,This pillow saved my back. I love the look and...
3,Home_and_Kitchen_5,1.0,CG,"Missing information on how to use it, but it i..."
4,Home_and_Kitchen_5,5.0,CG,Very nice set. Good quality. We have had the s...

In [34]:
df.rename(columns={"text_":"text"},inplace=True)
df["label"]=(df["label"]=="CG").astype(int)
df.drop(["category","rating"],axis=1,inplace=True)

In [35]:
df.head()

   label                                               text
0      1  Love this!  Well made, sturdy, and very comfor...
1      1  love it, a great upgrade from the original.  I...
2      1  This pillow saved my back. I love the look and...
3      1  Missing information on how to use it, but it i...
4      1  Very nice set. Good quality. We have had the s...

In [36]:
df['label'].value_counts()

label
1    20216
0    20216
Name: count, dtype: int64

In [37]:
df[df['label']==0]['label']

55       0
56       0
57       0
58       0
59       0
        ..
40423    0
40425    0
40427    0
40429    0
40431    0
Name: label, Length: 20216, dtype: int64

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40432 entries, 0 to 40431
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   40432 non-null  int64
 1   text    40432 non-null  str
dtypes: int64(1), str(1)
memory usage: 631.9 KB