In [1]:
import pandas as pd
import numpy as np

In [3]:
PATH=r"C:\Users\LENOVO\Desktop\Shopping\AI_Shopping_Intelligence\data\raw\Main_review.csv"

In [5]:
df=pd.read_csv(PATH)
df.head()

,category,rating,label,text_
0,Home_and_Kitchen_5,5.0,CG,"Love this! Well made, sturdy, and very comfor..."
1,Home_and_Kitchen_5,5.0,CG,"love it, a great upgrade from the original. I..."
2,Home_and_Kitchen_5,5.0,CG,This pillow saved my back. I love the look and...
3,Home_and_Kitchen_5,1.0,CG,"Missing information on how to use it, but it i..."
4,Home_and_Kitchen_5,5.0,CG,Very nice set. Good quality. We have had the s...

In [10]:
df.rename(columns={"text_":"text"},inplace=True)
df["label"]=df["label"].apply(lambda x: 1 if x=="OG" else 0)

In [11]:
df.head()

,category,rating,label,text
0,Home_and_Kitchen_5,5.0,0,"Love this! Well made, sturdy, and very comfor..."
1,Home_and_Kitchen_5,5.0,0,"love it, a great upgrade from the original. I..."
2,Home_and_Kitchen_5,5.0,0,This pillow saved my back. I love the look and...
3,Home_and_Kitchen_5,1.0,0,"Missing information on how to use it, but it i..."
4,Home_and_Kitchen_5,5.0,0,Very nice set. Good quality. We have had the s...

In [12]:
df['label'].value_counts()

label
0    40432
Name: count, dtype: int64

In [15]:
df[df['label']==0]['label']

0        0
1        0
2        0
3        0
4        0
        ..
40427    0
40428    0
40429    0
40430    0
40431    0
Name: label, Length: 40432, dtype: int64