In [151]:
import pandas as pd
import numpy as np  
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from flaml import AutoML
from sklearn.metrics import accuracy_score

In [152]:
PATH=r"C:\Users\LENOVO\Desktop\Shopping\AI_Shopping_Intelligence\data\raw\Main_review.csv"

In [153]:
df=pd.read_csv(PATH)
df.head()

,category,rating,label,text_
0,Home_and_Kitchen_5,5.0,CG,"Love this! Well made, sturdy, and very comfor..."
1,Home_and_Kitchen_5,5.0,CG,"love it, a great upgrade from the original. I..."
2,Home_and_Kitchen_5,5.0,CG,This pillow saved my back. I love the look and...
3,Home_and_Kitchen_5,1.0,CG,"Missing information on how to use it, but it i..."
4,Home_and_Kitchen_5,5.0,CG,Very nice set. Good quality. We have had the s...

In [154]:
# df.rename(columns={"text_":"text"},inplace=True)
# df["label"]=df["label"].apply(lambda x: '0' if x=="CG" else '1')
# df["label"]=df["label"].astype(int)

In [155]:
df.rename(columns={"text_":"text"},inplace=True)
df["label"] = (df["label"] == "CG").astype(int)

In [156]:
df.head()

,category,rating,label,text
0,Home_and_Kitchen_5,5.0,1,"Love this! Well made, sturdy, and very comfor..."
1,Home_and_Kitchen_5,5.0,1,"love it, a great upgrade from the original. I..."
2,Home_and_Kitchen_5,5.0,1,This pillow saved my back. I love the look and...
3,Home_and_Kitchen_5,1.0,1,"Missing information on how to use it, but it i..."
4,Home_and_Kitchen_5,5.0,1,Very nice set. Good quality. We have had the s...

In [157]:
df['label'].value_counts()

label
1    20216
0    20216
Name: count, dtype: int64

In [158]:
df[df['label']==0]['label']
df.drop(columns=["category","rating"])

       label                                               text
0          1  Love this!  Well made, sturdy, and very comfor...
1          1  love it, a great upgrade from the original.  I...
2          1  This pillow saved my back. I love the look and...
3          1  Missing information on how to use it, but it i...
4          1  Very nice set. Good quality. We have had the s...
...      ...                                                ...
40427      0  I had read some reviews saying that this bra r...
40428      1  I wasn't sure exactly what it would be. It is ...
40429      0  You can wear the hood by itself, wear it with ...
40430      1  I liked nothing about this dress. The only rea...
40431      0  I work in the wedding industry and have to wor...

[40432 rows x 2 columns]

In [159]:
features=df["text"]
target=df['label']

In [160]:
tf_idf=TfidfVectorizer()
x_vectorized=tf_idf.fit_transform(features)

In [161]:
x_train,x_test,y_train,y_test=train_test_split(
    x_vectorized,
    target,
    test_size=0.2,
    random_state=42
)
# x_test=tf_idf.transform(x_test)
model=AutoML()

In [162]:
model.fit(
    x_train,
    y_train,
    task="classification",
    time_budget=300
)

[flaml.automl.logger: 07-26 16:47:13] {2375} INFO - task = classification
[flaml.automl.logger: 07-26 16:47:13] {2386} INFO - Evaluation method: holdout
[flaml.automl.logger: 07-26 16:47:13] {2489} INFO - Minimizing error metric: 1-roc_auc
[flaml.automl.logger: 07-26 16:47:13] {2606} INFO - List of ML learners in AutoML Run: ['lgbm', 'rf', 'xgboost', 'extra_tree', 'xgb_limitdepth', 'sgd', 'lrl1']
[flaml.automl.logger: 07-26 16:47:13] {2911} INFO - iteration 0, current learner lgbm
[flaml.automl.logger: 07-26 16:47:15] {3046} INFO - Estimated sufficient time budget=18071s. Estimated necessary time budget=418s.
[flaml.automl.logger: 07-26 16:47:15] {3097} INFO -  at 1.9s,	estimator lgbm's best error=2.4478e-01,	best estimator lgbm's best error=2.4478e-01
[flaml.automl.logger: 07-26 16:47:15] {2911} INFO - iteration 1, current learner lgbm
[flaml.automl.logger: 07-26 16:47:16] {3097} INFO -  at 3.7s,	estimator lgbm's best error=2.3098e-01,	best estimator lgbm's best error=2.3098e-01
[flaml.automl.logger: 07-26 16:47:16] {2911} INFO - iteration 2, current learner sgd
[flaml.automl.logger: 07-26 16:47:32] {3097} INFO -  at 19.0s,	estimator sgd's best error=8.0275e-02,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:32] {2911} INFO - iteration 3, current learner xgboost
[flaml.automl.logger: 07-26 16:47:33] {3097} INFO -  at 19.9s,	estimator xgboost's best error=2.3841e-01,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:33] {2911} INFO - iteration 4, current learner xgboost
[flaml.automl.logger: 07-26 16:47:33] {3097} INFO -  at 20.8s,	estimator xgboost's best error=2.3841e-01,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:33] {2911} INFO - iteration 5, current learner lgbm
[flaml.automl.logger: 07-26 16:47:36] {3097} INFO -  at 23.2s,	estimator lgbm's best error=2.3098e-01,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:36] {2911} INFO - iteration 6, current learner xgboost
[flaml.automl.logger: 07-26 16:47:37] {3097} INFO -  at 24.0s,	estimator xgboost's best error=1.8806e-01,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:37] {2911} INFO - iteration 7, current learner extra_tree
[flaml.automl.logger: 07-26 16:47:37] {3097} INFO -  at 24.3s,	estimator extra_tree's best error=4.7067e-01,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:37] {2911} INFO - iteration 8, current learner extra_tree
[flaml.automl.logger: 07-26 16:47:37] {3097} INFO -  at 24.6s,	estimator extra_tree's best error=3.8814e-01,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:37] {2911} INFO - iteration 9, current learner xgboost
[flaml.automl.logger: 07-26 16:47:38] {3097} INFO -  at 24.9s,	estimator xgboost's best error=1.7651e-01,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:38] {2911} INFO - iteration 10, current learner xgboost
[flaml.automl.logger: 07-26 16:47:39] {3097} INFO -  at 26.0s,	estimator xgboost's best error=1.6840e-01,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:39] {2911} INFO - iteration 11, current learner extra_tree
[flaml.automl.logger: 07-26 16:47:39] {3097} INFO -  at 26.3s,	estimator extra_tree's best error=3.8814e-01,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:39] {2911} INFO - iteration 12, current learner rf
[flaml.automl.logger: 07-26 16:47:39] {3097} INFO -  at 26.6s,	estimator rf's best error=3.5223e-01,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:39] {2911} INFO - iteration 13, current learner rf
[flaml.automl.logger: 07-26 16:47:40] {3097} INFO -  at 27.0s,	estimator rf's best error=2.5543e-01,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:40] {2911} INFO - iteration 14, current learner rf
[flaml.automl.logger: 07-26 16:47:40] {3097} INFO -  at 27.6s,	estimator rf's best error=2.5543e-01,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:40] {2911} INFO - iteration 15, current learner rf
[flaml.automl.logger: 07-26 16:47:41] {3097} INFO -  at 28.3s,	estimator rf's best error=2.2558e-01,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:41] {2911} INFO - iteration 16, current learner extra_tree
[flaml.automl.logger: 07-26 16:47:42] {3097} INFO -  at 29.1s,	estimator extra_tree's best error=3.4693e-01,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:42] {2911} INFO - iteration 17, current learner rf
[flaml.automl.logger: 07-26 16:47:42] {3097} INFO -  at 29.7s,	estimator rf's best error=2.2218e-01,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:42] {2911} INFO - iteration 18, current learner sgd
[flaml.automl.logger: 07-26 16:47:45] {3097} INFO -  at 32.3s,	estimator sgd's best error=8.0275e-02,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:45] {2911} INFO - iteration 19, current learner lgbm
[flaml.automl.logger: 07-26 16:47:47] {3097} INFO -  at 34.6s,	estimator lgbm's best error=1.8502e-01,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:47] {2911} INFO - iteration 20, current learner extra_tree
[flaml.automl.logger: 07-26 16:47:48] {3097} INFO -  at 35.4s,	estimator extra_tree's best error=2.7312e-01,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:48] {2911} INFO - iteration 21, current learner extra_tree
[flaml.automl.logger: 07-26 16:47:49] {3097} INFO -  at 36.4s,	estimator extra_tree's best error=2.7312e-01,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:49] {2911} INFO - iteration 22, current learner extra_tree
[flaml.automl.logger: 07-26 16:47:50] {3097} INFO -  at 37.5s,	estimator extra_tree's best error=2.2281e-01,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:50] {2911} INFO - iteration 23, current learner lgbm
[flaml.automl.logger: 07-26 16:47:52] {3097} INFO -  at 39.0s,	estimator lgbm's best error=1.8502e-01,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:52] {2911} INFO - iteration 24, current learner rf
[flaml.automl.logger: 07-26 16:47:52] {3097} INFO -  at 39.8s,	estimator rf's best error=1.9035e-01,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:52] {2911} INFO - iteration 25, current learner extra_tree
[flaml.automl.logger: 07-26 16:47:55] {3097} INFO -  at 42.7s,	estimator extra_tree's best error=1.1405e-01,	best estimator sgd's best error=8.0275e-02
[flaml.automl.logger: 07-26 16:47:55] {2911} INFO - iteration 26, current learner sgd
[flaml.automl.logger: 07-26 16:47:58] {3097} INFO -  at 45.5s,	estimator sgd's best error=3.5286e-02,	best estimator sgd's best error=3.5286e-02
[flaml.automl.logger: 07-26 16:47:58] {2911} INFO - iteration 27, current learner xgboost
[flaml.automl.logger: 07-26 16:48:00] {3097} INFO -  at 47.1s,	estimator xgboost's best error=1.6840e-01,	best estimator sgd's best error=3.5286e-02
[flaml.automl.logger: 07-26 16:48:00] {2911} INFO - iteration 28, current learner sgd
[flaml.automl.logger: 07-26 16:48:07] {3097} INFO -  at 54.8s,	estimator sgd's best error=3.3464e-02,	best estimator sgd's best error=3.3464e-02
[flaml.automl.logger: 07-26 16:48:07] {2911} INFO - iteration 29, current learner sgd
[flaml.automl.logger: 07-26 16:48:15] {3097} INFO -  at 61.9s,	estimator sgd's best error=3.1898e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:48:15] {2911} INFO - iteration 30, current learner sgd
[flaml.automl.logger: 07-26 16:48:29] {3097} INFO -  at 76.7s,	estimator sgd's best error=3.1898e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:48:29] {2911} INFO - iteration 31, current learner rf
[flaml.automl.logger: 07-26 16:48:30] {3097} INFO -  at 77.3s,	estimator rf's best error=1.9035e-01,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:48:30] {2911} INFO - iteration 32, current learner lgbm
[flaml.automl.logger: 07-26 16:48:33] {3097} INFO -  at 80.0s,	estimator lgbm's best error=1.5690e-01,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:48:33] {2911} INFO - iteration 33, current learner rf
[flaml.automl.logger: 07-26 16:48:34] {3097} INFO -  at 81.4s,	estimator rf's best error=1.2494e-01,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:48:34] {2911} INFO - iteration 34, current learner sgd
[flaml.automl.logger: 07-26 16:48:44] {3097} INFO -  at 91.1s,	estimator sgd's best error=3.1898e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:48:44] {2911} INFO - iteration 35, current learner rf
[flaml.automl.logger: 07-26 16:48:45] {3097} INFO -  at 92.0s,	estimator rf's best error=1.2494e-01,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:48:45] {2911} INFO - iteration 36, current learner extra_tree
[flaml.automl.logger: 07-26 16:48:46] {3097} INFO -  at 93.5s,	estimator extra_tree's best error=1.1405e-01,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:48:46] {2911} INFO - iteration 37, current learner sgd
[flaml.automl.logger: 07-26 16:48:56] {3097} INFO -  at 103.0s,	estimator sgd's best error=3.1898e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:48:56] {2911} INFO - iteration 38, current learner extra_tree
[flaml.automl.logger: 07-26 16:48:57] {3097} INFO -  at 104.7s,	estimator extra_tree's best error=1.1405e-01,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:48:57] {2911} INFO - iteration 39, current learner extra_tree
[flaml.automl.logger: 07-26 16:49:02] {3097} INFO -  at 109.5s,	estimator extra_tree's best error=1.0228e-01,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:49:02] {2911} INFO - iteration 40, current learner rf
[flaml.automl.logger: 07-26 16:49:03] {3097} INFO -  at 110.4s,	estimator rf's best error=1.2494e-01,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:49:03] {2911} INFO - iteration 41, current learner rf
[flaml.automl.logger: 07-26 16:49:05] {3097} INFO -  at 112.6s,	estimator rf's best error=8.9921e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:49:05] {2911} INFO - iteration 42, current learner sgd
[flaml.automl.logger: 07-26 16:49:13] {3097} INFO -  at 120.6s,	estimator sgd's best error=3.1898e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:49:13] {2911} INFO - iteration 43, current learner lgbm
[flaml.automl.logger: 07-26 16:49:15] {3097} INFO -  at 122.6s,	estimator lgbm's best error=1.5690e-01,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:49:15] {2911} INFO - iteration 44, current learner xgboost
[flaml.automl.logger: 07-26 16:49:18] {3097} INFO -  at 125.1s,	estimator xgboost's best error=9.0067e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:49:18] {2911} INFO - iteration 45, current learner sgd
[flaml.automl.logger: 07-26 16:49:26] {3097} INFO -  at 133.1s,	estimator sgd's best error=3.1898e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:49:26] {2911} INFO - iteration 46, current learner xgboost
[flaml.automl.logger: 07-26 16:49:28] {3097} INFO -  at 135.8s,	estimator xgboost's best error=7.0022e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:49:28] {2911} INFO - iteration 47, current learner rf
[flaml.automl.logger: 07-26 16:49:30] {3097} INFO -  at 137.2s,	estimator rf's best error=8.9921e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:49:30] {2911} INFO - iteration 48, current learner xgboost
[flaml.automl.logger: 07-26 16:49:32] {3097} INFO -  at 139.8s,	estimator xgboost's best error=7.0022e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:49:32] {2911} INFO - iteration 49, current learner lgbm
[flaml.automl.logger: 07-26 16:49:34] {3097} INFO -  at 141.8s,	estimator lgbm's best error=1.5690e-01,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:49:34] {2911} INFO - iteration 50, current learner rf
[flaml.automl.logger: 07-26 16:49:39] {3097} INFO -  at 146.7s,	estimator rf's best error=7.6130e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:49:39] {2911} INFO - iteration 51, current learner sgd
[flaml.automl.logger: 07-26 16:49:40] {3097} INFO -  at 147.2s,	estimator sgd's best error=3.1898e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:49:40] {2911} INFO - iteration 52, current learner rf
[flaml.automl.logger: 07-26 16:49:43] {3097} INFO -  at 150.2s,	estimator rf's best error=7.6130e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:49:43] {2911} INFO - iteration 53, current learner xgboost
[flaml.automl.logger: 07-26 16:49:50] {3097} INFO -  at 157.4s,	estimator xgboost's best error=5.0005e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:49:50] {2911} INFO - iteration 54, current learner rf
[flaml.automl.logger: 07-26 16:49:58] {3097} INFO -  at 165.1s,	estimator rf's best error=7.6130e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:49:58] {2911} INFO - iteration 55, current learner lgbm
[flaml.automl.logger: 07-26 16:50:03] {3097} INFO -  at 170.0s,	estimator lgbm's best error=1.3518e-01,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:50:03] {2911} INFO - iteration 56, current learner xgboost
[flaml.automl.logger: 07-26 16:50:05] {3097} INFO -  at 172.8s,	estimator xgboost's best error=5.0005e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:50:05] {2911} INFO - iteration 57, current learner rf
[flaml.automl.logger: 07-26 16:50:13] {3097} INFO -  at 180.4s,	estimator rf's best error=6.6401e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:50:13] {2911} INFO - iteration 58, current learner xgboost
[flaml.automl.logger: 07-26 16:50:16] {3097} INFO -  at 183.8s,	estimator xgboost's best error=5.0005e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:50:16] {2911} INFO - iteration 59, current learner xgboost
[flaml.automl.logger: 07-26 16:50:32] {3097} INFO -  at 198.9s,	estimator xgboost's best error=3.8809e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:50:32] {2911} INFO - iteration 60, current learner lgbm
[flaml.automl.logger: 07-26 16:50:35] {3097} INFO -  at 202.0s,	estimator lgbm's best error=1.3518e-01,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:50:35] {2911} INFO - iteration 61, current learner xgboost
[flaml.automl.logger: 07-26 16:50:52] {3097} INFO -  at 219.0s,	estimator xgboost's best error=3.8809e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:50:52] {2911} INFO - iteration 62, current learner rf
[flaml.automl.logger: 07-26 16:50:56] {3097} INFO -  at 223.6s,	estimator rf's best error=6.6401e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:50:56] {2911} INFO - iteration 63, current learner extra_tree
[flaml.automl.logger: 07-26 16:50:59] {3097} INFO -  at 226.3s,	estimator extra_tree's best error=1.0228e-01,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:50:59] {2911} INFO - iteration 64, current learner sgd
[flaml.automl.logger: 07-26 16:50:59] {3097} INFO -  at 226.6s,	estimator sgd's best error=3.1898e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:50:59] {2911} INFO - iteration 65, current learner lgbm
[flaml.automl.logger: 07-26 16:51:17] {3097} INFO -  at 244.0s,	estimator lgbm's best error=6.7485e-02,	best estimator sgd's best error=3.1898e-02
[flaml.automl.logger: 07-26 16:51:17] {2911} INFO - iteration 66, current learner lgbm
[flaml.automl.logger: 07-26 16:51:39] {3097} INFO -  at 266.3s,	estimator lgbm's best error=2.8333e-02,	best estimator lgbm's best error=2.8333e-02
[flaml.automl.logger: 07-26 16:51:39] {2911} INFO - iteration 67, current learner xgboost
[flaml.automl.logger: 07-26 16:51:59] {3097} INFO -  at 286.8s,	estimator xgboost's best error=3.6810e-02,	best estimator lgbm's best error=2.8333e-02
[flaml.automl.logger: 07-26 16:51:59] {2911} INFO - iteration 68, current learner xgb_limitdepth
[flaml.automl.logger: 07-26 16:52:04] {3097} INFO -  at 291.3s,	estimator xgb_limitdepth's best error=8.6843e-02,	best estimator lgbm's best error=2.8333e-02
[flaml.automl.logger: 07-26 16:52:04] {2911} INFO - iteration 69, current learner xgb_limitdepth
[flaml.automl.logger: 07-26 16:52:09] {3097} INFO -  at 295.9s,	estimator xgb_limitdepth's best error=8.6843e-02,	best estimator lgbm's best error=2.8333e-02
[flaml.automl.logger: 07-26 16:52:09] {2911} INFO - iteration 70, current learner lrl1

c:\Users\LENOVO\Desktop\Shopping\myvenv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\LENOVO\Desktop\Shopping\myvenv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\LENOVO\Desktop\Shopping\myvenv\Lib\site-packages\sklearn\linear_model\_logistic.py:1457: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

[flaml.automl.logger: 07-26 16:52:24] {3097} INFO -  at 311.4s,	estimator lrl1's best error=4.2590e-02,	best estimator lgbm's best error=2.8333e-02

c:\Users\LENOVO\Desktop\Shopping\myvenv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[flaml.automl.logger: 07-26 16:52:50] {3359} INFO - retrain lgbm for 25.9s
[flaml.automl.logger: 07-26 16:52:50] {3362} INFO - retrained model: LGBMClassifier(colsample_bytree=np.float64(0.40989107964524396),
               learning_rate=np.float64(0.10577750092292157), max_bin=1023,
               min_child_samples=7, n_estimators=233, n_jobs=-1, num_leaves=24,
               reg_alpha=0.0009765625, reg_lambda=0.0009765625, verbose=-1)
[flaml.automl.logger: 07-26 16:52:50] {2636} INFO - fit succeeded
[flaml.automl.logger: 07-26 16:52:50] {2637} INFO - Time taken to find the best model: 266.31008982658386

In [163]:
model.model

LGBMEstimator(_estimator_type='classifier',
              colsample_bytree=np.float64(0.40989107964524396),
              learning_rate=np.float64(0.10577750092292157), max_bin=1023,
              min_child_samples=7, n_estimators=233, n_jobs=-1, num_leaves=24,
              reg_alpha=0.0009765625, reg_lambda=0.0009765625,
              task=<flaml.automl.task.generic_task.GenericTask object at 0x000002395C2ED310>,
              verbose=-1)

In [164]:
model.best_estimator

'lgbm'

In [165]:
model.best_loss

0.02833314222375105

In [166]:
prediction=model.predict(x_test)
accuracy = accuracy_score(y_test, prediction)
print(f"Accuracy: {accuracy:.4f}")

Accuracy: 0.9087